### PR TITLE
bulk update from upstream

### PR DESCRIPTION
**Pull request by nardholio**

### CODE REVIEW

**Comment by kornyone** [comment]
Holy crap 5 year old pull request.  I got an email notification and at first was like "thefawq they doing still working on that phone!". :)

Hope things are well, dunno where other folks wound up online from the team - I stopped using freenode when I left Texas in 2013

**Comment by lbdroid** [comment]
Hey man, long time no hear from.
Yeah, everyone has moved on to better and better things.
Except apparently for nardholio, into same old same old. :)

**Comment by mdmallardi** [comment]
Hah. Good to know you folks are still doing well!

**Comment by nardholio** [comment]
Haha. Glad to see you are all still alive. I'm waiting for the fxtec pro1
to come out. I was also looking at Gemini PDA but I don't like it's form
factor and it's expensive as hell despite already being a year old.

**Comment by aglasgall** [comment]
Whoa, you're all still around.

**Pull request closed without merging**
